### PR TITLE
(chore) CI - fix module not found

### PR DESCRIPTION
**Pull request by hebus**
Hope this fix the issue

### CODE REVIEW

**Review by Mathieu-Steininger — APPROVED** [review]
ok

**Review by ericleib — COMMENTED** [review]
I think the problem is that you updated the @sinequa libraries but you did not include the update of the package and package-lock in your PR (your version has 11.9.1-DEV.267 which is from 24 days ago).

**Comment by hebus** [comment]
> I think the problem is that you updated the @sinequa libraries but you did not include the update of the package and package-lock in your PR (your version has 11.9.1-DEV.267 which is from 24 days ago).

Right, the connection with npm.sinequa.com in my .npmrc was https://npm.sinequa.com:4873 instead of http://npm.snequa.com:4873

**Review by ericleib — COMMENTED** [review]
There is a huge number of changes in the package-lock, but I would expect only the sinequa libraries to be updated. Are you sure it's normal ?

**Review by ericleib — APPROVED** [review]

**Comment by hebus** [comment]
> There is a huge number of changes in the package-lock, but I would expect only the sinequa libraries to be updated. Are you sure it's normal ?

Just to test if CI works.
Now, the package-lock file contains less changes

**Pull request merged**
